language: java
jdk:
  - oraclejdk8
addons:
  apt:
    packages:
      - oracle-java8-installer
notifications:
  email:
    recipients:
      - marcelomastroianni@gmail.com
      - jazminsofiaf@gmail.com
      - ariel.manzione@yahoo.com.ar
      - nicodec_89@hotmail.com
      - ari-man_77@hotmail.com
    on_success: always
    on_failure: always
